name: flutter_KENNY_BOCCANEDES
description: Proyecto Flutter básico para evaluación académica
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true